### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by icemac** [collective/collective.recipe.backup#31]
It would be nice if this package would support Python 3, too.

**Comment by mauritsvanrees** [comment]
I have released 4.0b3 with basic support for Python 3. The tests don't run with it yet, because the order of the output differs a bit, and because some tests use `plone.recipe.zope2instance`, which has no Python 3 compatible release.
So there is progress, but I will leave this issue open.

**Comment by mauritsvanrees** [comment]
Python 3.6 is working since version 4.0.
Travis is currently green on Python 2.7, 3.6, 3.7.

But we are still ignoring the [`zope2instance` tests on Python 3](https://github.com/collective/collective.recipe.backup/blob/4.0.1/src/collective/recipe/backup/tests/test_docs.py#L111). At first this was because there was not yet a Python 3 compatible `plone.recipe.zope2instance` release, and then the same for `mailinglogger`.

That is no longer a problem, but a compatible zope2instance recipe would pull in ZODB, Zope, Plone, which is too much for what we want to test in there: can we read some options (blobstorage, filestorage, var) from a recipe section? I tried enabling the test locally, but quickly ran into errors compiling Persistence. Maybe we need to load the Plone version pins, or whatever.  But it is too much of a bother like this.
I guess there is room here to solve this with a mock recipe, but let's not.

We will stick to only testing this part on Python 2.7, and with an older version (3.9) of `plone.recipe.zope2instance`, which does not pull in so many packages.
