### ISSUE TITLE
[question] Backing up Encrypted FileStorage?

### ISSUE THREAD

**Issue by riker1** [collective/collective.recipe.backup#43]
I am using [cipher.encyrptingstorage](https://github.com/zopefoundation/cipher.encryptingstorage) for a special project that requires non-public data to be secure both in flight and at rest. 

Currently, I'm backing up the machine via disk-copy and tape but, would like to use the automated scripts that I use on other Plone sites I run. Encryptingstorage pretty much leaves locations intact but Data.fs is renamed to encrypted.fs Blobstorage is now in a new folder named blob-storage-enc.

**Comment by mauritsvanrees** [comment]
I have not used encrypted storage.

One thing to try is if you can get `encrypted.fs` backed up by specifying it in `additional_filestorages`. See https://github.com/collective/collective.recipe.backup#advanced-usage-multiple-data-fs-files

If the backup fails because there is no `Data.fs` file, then you could try simply adding an empty `Data.fs` file, or maybe a real `Data.fs` file from a project where you have not added anything in the database yet. Or maybe make it a symlink to `encrypted.fs`.

You would need to see what happens when you make changes in your encrypted database: are the changes backed up or are they somehow ignored because there are no changes in `Data.fs`?

And try a restore too.
